In [1]:
from einops import rearrange
import torch

input_tensor=torch.randn(1,2,3)

# rearrange elements according to the pattern
output_tensor = rearrange(input_tensor, 'h w c -> c h w')   # 进行维度的调换

print(input_tensor)
print(output_tensor)
print(input_tensor.shape)
print(output_tensor.shape)

tensor([[[-0.4916, -0.7328,  0.3370],
         [ 0.7968, -0.4508, -1.0111]]])
tensor([[[-0.4916,  0.7968]],

        [[-0.7328, -0.4508]],

        [[ 0.3370, -1.0111]]])
torch.Size([1, 2, 3])
torch.Size([3, 1, 2])


In [4]:
a = torch.randn(1, 4, 3)  # [1, 4, 3]
output = rearrange(a, 'c (r p) w -> c r p w', p=2) # 中间维度看作r×p，然后给出p的数值，这样会自动把中间那个维度拆解成3×3
print(output.shape)   # [1, 2, 2, 3]

print(a)
print(output)

torch.Size([1, 2, 2, 3])
tensor([[[ 0.3865, -1.7265,  0.1809],
         [-0.0750,  0.2128,  0.5375],
         [ 0.7706,  0.7358, -0.3090],
         [-1.2844, -2.0029, -0.2475]]])
tensor([[[[ 0.3865, -1.7265,  0.1809],
          [-0.0750,  0.2128,  0.5375]],

         [[ 0.7706,  0.7358, -0.3090],
          [-1.2844, -2.0029, -0.2475]]]])


In [6]:
from einops import repeat
a = torch.randn(9, 9)  # [9, 9]
output_tensor = repeat(a, 'h w -> c h w', c=3)  # [3, 9, 9]
print(output_tensor.shape)

torch.Size([3, 9, 9])


In [21]:
from einops import reduce
 
x = torch.randn(100, 32, 64)
# perform max-reduction on the first axis:
y0 = reduce(x, 't b c -> b c', reduction='max') #(32, 64)
print(y0.shape)
 
#指定h2,w2，相当于指定池化核的大小
x1 = torch.randn(10, 512, 30, 40)
# 2d max-pooling with kernel size = 2 * 2 
y1 = reduce(x1, 'b c (h1 h2) (w1 w2) -> b c h1 w1', 'max', h2=2, w2=2)#(10, 512, 15, 20)
print(y1.shape)
 
# go back to the original height and width
y2 = rearrange(y1, 'b (c h2 w2) h1 w1 -> b c (h1 h2) (w1 w2)', h2=2, w2=2)#(10, 128, 30, 40)
print(y2.shape)

#指定h1,w1，相当于指定池化后张量的大小
# 2d max-pooling to 10 * 20 grid:
y3 = reduce(x1, 'b c (h1 h2) (w1 w2) -> b c h1 w1', 'max', h1=10, w1=20) #(10, 512, 10, 20)
print(y3.shape)
 
# 2d average-pooling to 10 * 20 grid:
y4 = reduce(x1, 'b c (h1 h2) (w1 w2) -> b c h1 w1', 'mean', h1=10, w1=20) #(10, 512, 10, 20)
print(y4.shape)
# Global average pooling
y5 = reduce(x1, 'b c h w -> b c', 'mean') #(10, 512)
print(y5.shape)

torch.Size([32, 64])
torch.Size([10, 512, 15, 20])
torch.Size([10, 128, 30, 40])
torch.Size([10, 512, 10, 20])
torch.Size([10, 512, 10, 20])
torch.Size([10, 512])
